#!/usr/bin/python
# -*- coding:utf-8 -*-

# difficulty 0 - 10
aasia = {
	'Turkki' : { 'capital': 'Ankara', 'difficulty': 0.5 },
	'Georgia' : { 'capital': 'Tbilisi', 'difficulty': 1.5 },
	'Armenia' : { 'capital': 'Jerevan', 'difficulty': 1.5 },
	'Azerbaidžan' : { 'capital': 'Baku', 'difficulty': 1.2 },
	'Syyria' : { 'capital': 'Damaskos', 'difficulty': 0.8 },
	'Libanon' : { 'capital': 'Beirut', 'difficulty': 1.2 },
	'Israel' : { 'capital': 'Jerusalem', 'difficulty': 0.5 },
	'Jordania' : { 'capital': 'Amman', 'difficulty': 1.5 },
	'Saudi-Arabia' : { 'capital': 'Riad', 'difficulty': 1.0 },
	'Jemen' : { 'capital': 'Sanaá', 'difficulty': 1.5 },
	'Oman' : { 'capital': 'Masqat', 'difficulty': 1.5 },
	'Yhdistyneet arabiemiirikunnat' : { 'capital': 'Abu Dhabi', 'difficulty': 1.0 },
	'Qatar' : { 'capital': 'Doha', 'difficulty': 1.2 },
	'Bahrain' : { 'capital': 'Manama', 'difficulty': 1.5 },
	'Kuwait' : { 'capital': 'Kuwait', 'difficulty': 0.5 },
	'Irak' : { 'capital': 'Bagdad', 'difficulty': 1.0 },
	'Iran' : { 'capital': 'Teheran', 'difficulty': 1.0 },
	'Turkmenistan' : { 'capital': 'Ašgabat', 'difficulty': 1.2 },
	'Uzbekistan' : { 'capital': 'Taškent', 'difficulty': 1.4 },
	'Afganistan' : { 'capital': 'Kabul', 'difficulty': 1.2 },
	'Pakistan' : { 'capital': 'Islamabad', 'difficulty': 1.2 },
	'Kazakstan' : { 'capital': 'Astana', 'difficulty': 1.0 },
	'Tadžikistan' : { 'capital': 'Dušanbe', 'difficulty': 1.5 },
	'Kirgisia' : { 'capital': 'Biškek', 'difficulty': 1.0 },
	'Intia' : { 'capital': 'New Delhi', 'difficulty': 0.5 },
	'Malediivit' : { 'capital': 'Malé', 'difficulty': 1.5 },
	'Sri Lanka' : { 'capital': 'Kotte', 'difficulty': 1.2 },
	'Nepal' : { 'capital': 'Kathmandu', 'difficulty': 0.5 },
	'Bhutan' : { 'capital': 'Thimphu', 'difficulty': 1.0 },
	'Bangladesh' : { 'capital': 'Dhaka', 'difficulty': 1.0 },
	'Kiina' : { 'capital': 'Peking', 'difficulty': 0.2 },
	'Mongolia' : { 'capital': 'Ulan Bator', 'difficulty': 1.2 },
	'Myanmar' : { 'capital': 'Naypyidaw', 'difficulty': 1.4 },
	'Thaimaa' : { 'capital': 'Bangkok', 'difficulty': 1.2 },
	'Laos' : { 'capital': 'Vientiane', 'difficulty': 1.2 },
	'Kambodža' : { 'capital': 'Phnom Penh', 'difficulty': 1.5 },
	'Vietnam' : { 'capital': 'Hanoi', 'difficulty': 1.0 },
	'Malesia' : { 'capital': 'Kuala Lumpur', 'difficulty': 1.2 },
	'Singapore' : { 'capital': 'Singapore', 'difficulty': 0.5 },
	'Indonesia' : { 'capital': 'Jakarta', 'difficulty': 1.4 },
	'Filippiinit' : { 'capital': 'Manila', 'difficulty': 1.5 },
	'Taiwan' : { 'capital': 'Taipei', 'difficulty': 0.5 },
	'Pohjois-Korea' : { 'capital': 'Pjongjang', 'difficulty': 1.4 },
	'Etelä-Korea' : { 'capital': 'Soul', 'difficulty': 1.0 },
	'Japani' : { 'capital': 'Tokio', 'difficulty': 0.5 },
	'Itä-Timor' : { 'capital': 'Dili', 'difficulty': 1.5 },
	'Brunei' : { 'capital': 'Bandar Seri Begawan', 'difficulty': 1.5 },
}
